version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
    environment:
      - OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
      - NEXT_PUBLIC_OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/exports:/app/public/exports
      - ./public/backups:/app/public/backups
      - indexeddb-data:/app/.next/cache/indexeddb
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
    driver: local
  indexeddb-data:
    driver: local 